CREATE TABLE Employee(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
FirstName VARCHAR(20) NOT NULL,
LastName VARCHAR(20) NOT NULL,
Gender VARCHAR(7) NOT NULL,
DOB DATE NOT NULL,
Salutation VARCHAR(20) NOT NULL,
Designation VARCHAR(20) NOT NULL,
Email VARCHAR(20) NOT NULL,
Mobile INT UNSIGNED NOT NULL,
AddressLine1 VARCHAR(20) NOT NULL,
AddressLine2 VARCHAR(20) NOT NULL,
City VARCHAR(20) NOT NULL,
State VARCHAR(20) NOT NULL,
Pin INT UNSIGNED NOT NULL,
Country VARCHAR(20) NOT NULL
);

